[[CHICKEN]]
arch = "aarch64"
git-tree-sha1 = "36a980b9c7e88054a69b5fe754935f209dc33616"
os = "macos"

    [[CHICKEN.download]]
    sha256 = "245fd2e00c18e4c51f1b025e56cb4fb9a799b7f34fdea8ea68bef81ea060fd7e"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.aarch64-apple-darwin.tar.gz"
[[CHICKEN]]
arch = "aarch64"
git-tree-sha1 = "47878dbc26e1f6245cfafb56f8227635f46d2905"
libc = "glibc"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "ea9b2ebcd64a4d0c82aa96ba0f293b435459f90e72f0a7851b2528b02875cc87"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.aarch64-linux-gnu.tar.gz"
[[CHICKEN]]
arch = "aarch64"
git-tree-sha1 = "4e7c2209412f1621c17c5cbbe2a51d62d3ccb20c"
libc = "musl"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "ccf5d5d5102a60607d98bcdc5519388579d8041becbe31c172c2bf21194ca8b8"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.aarch64-linux-musl.tar.gz"
[[CHICKEN]]
arch = "aarch64"
git-tree-sha1 = "9bfdf4a201fb8baded9dc15e5cb7e9c8633bda8e"
os = "freebsd"

    [[CHICKEN.download]]
    sha256 = "3976ef8d86c6905537c782c8f718365f8a85923af9cb87b02207da138548bcb6"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.aarch64-unknown-freebsd.tar.gz"
[[CHICKEN]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a40f1b0b4d43b463f92a99899f1db513ef0b87a6"
libc = "glibc"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "69989b511d4765152c281e3cafc64f9a6a5387040121fb90e9cbb1b6452df49d"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.armv6l-linux-gnueabihf.tar.gz"
[[CHICKEN]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a9e5145564d4543454576c1133d7b162383c6da"
libc = "musl"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "e074125d5ec79d3448a6ecc91aad947fc632d5369bfea64f1be95e06627e60d8"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.armv6l-linux-musleabihf.tar.gz"
[[CHICKEN]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ae68b78c43a4eaa163b872bf4b86e2e3f7ee12a"
libc = "glibc"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "ddfd1daedf17e917f5c56804ce4a2e7dee8c8eb0736be87891e4b9985a0bc968"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.armv7l-linux-gnueabihf.tar.gz"
[[CHICKEN]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3b82f352f8b135a538e12085012cad0d60f58760"
libc = "musl"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "526ee7d706d2fd01d3d4208a820ee874d520e05e711ec94bde193bd2ee075aec"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.armv7l-linux-musleabihf.tar.gz"
[[CHICKEN]]
arch = "i686"
git-tree-sha1 = "d542274449f6bec983c96ec3f48169d60dc2f879"
libc = "glibc"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "c73332645dca402d03b68493e66a2ea0c66e81a4892b37a545a46dc07635ed9c"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.i686-linux-gnu.tar.gz"
[[CHICKEN]]
arch = "i686"
git-tree-sha1 = "2b17919fee5009bd794d1267d403dc6b11ca514c"
libc = "musl"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "a75ea1d5a9e5ea601fd0a8e69ffa2ede5a565a55133b17c478dc91adf1c7d427"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.i686-linux-musl.tar.gz"
[[CHICKEN]]
arch = "i686"
git-tree-sha1 = "f9743d3ba701c6d4c27c971d4d45d040b84b31b3"
os = "windows"

    [[CHICKEN.download]]
    sha256 = "751c72b6c271f3b38ded0b2f9a471748b85bbf0b57bf905fb2a968a5f8865f21"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.i686-w64-mingw32.tar.gz"
[[CHICKEN]]
arch = "powerpc64le"
git-tree-sha1 = "bff7d9af109687a2f5ed2f2e1add9faebb2374f9"
libc = "glibc"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "dfb8b435e20c59052c8b2eab2332e6e936d17def958bdac44130ab24e83162c8"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.powerpc64le-linux-gnu.tar.gz"
[[CHICKEN]]
arch = "riscv64"
git-tree-sha1 = "14135ca6c423db96a24988953fce282ea00e5080"
libc = "glibc"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "75fda15f42246714275f0e075d043913a11830e768be95c6c63bed7d2373ba5f"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.riscv64-linux-gnu.tar.gz"
[[CHICKEN]]
arch = "x86_64"
git-tree-sha1 = "93798db3ff483690ca9e2ff208deb615ecf7aff7"
os = "macos"

    [[CHICKEN.download]]
    sha256 = "1e0bfa0fee7fae7ac51cd6755b45d3b651f65895df7ef751da40872944c5a643"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.x86_64-apple-darwin.tar.gz"
[[CHICKEN]]
arch = "x86_64"
git-tree-sha1 = "e5f1413964eae8066765666d8d2d9c9d5c4f03a1"
libc = "glibc"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "241652e1b2ff0680c632d034f6be27a5dd088f9d8e9ff528db98ef3474d9ea69"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.x86_64-linux-gnu.tar.gz"
[[CHICKEN]]
arch = "x86_64"
git-tree-sha1 = "6e2c10afc2671a179637e6ff347899c22de77e2f"
libc = "musl"
os = "linux"

    [[CHICKEN.download]]
    sha256 = "8553f52844dad99bc0a667c558c977dccc24297e31af86c969e43754f0f01a18"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.x86_64-linux-musl.tar.gz"
[[CHICKEN]]
arch = "x86_64"
git-tree-sha1 = "1ef77bc42c5964f81418c111898bdd07362357e5"
os = "freebsd"

    [[CHICKEN.download]]
    sha256 = "e475f82d1504858dfb874f4a7605eb682303e04fa98ae1b34b88d2872ff2b7e8"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.x86_64-unknown-freebsd.tar.gz"
[[CHICKEN]]
arch = "x86_64"
git-tree-sha1 = "2ac32f84bbf497e85dcb53edd1fba4371e60dce1"
os = "windows"

    [[CHICKEN.download]]
    sha256 = "07fb3e172e6b7100d2526c10c1652747093077a7e80844e617d21bdc1a6123d3"
    url = "https://github.com/JuliaBinaryWrappers/CHICKEN_jll.jl/releases/download/CHICKEN-v6.0.0+0/CHICKEN.v6.0.0.x86_64-w64-mingw32.tar.gz"
