# Autogenerated wrapper script for CHICKEN_jll for i686-linux-musl
export chicken, chicken_config_h, chicken_csc, chicken_csi, chicken_do, chicken_h, chicken_install, chicken_profile, chicken_status, chicken_uninstall, libchicken, libchicken_a

JLLWrappers.@generate_wrapper_header("CHICKEN")
JLLWrappers.@declare_executable_product(chicken)
JLLWrappers.@declare_file_product(chicken_config_h)
JLLWrappers.@declare_file_product(chicken_h)
JLLWrappers.@declare_library_product(libchicken, "libchicken.so.11")
JLLWrappers.@declare_executable_product(chicken_csc)
JLLWrappers.@declare_executable_product(chicken_csi)
JLLWrappers.@declare_executable_product(chicken_do)
JLLWrappers.@declare_executable_product(chicken_install)
JLLWrappers.@declare_executable_product(chicken_profile)
JLLWrappers.@declare_executable_product(chicken_status)
JLLWrappers.@declare_executable_product(chicken_uninstall)
JLLWrappers.@declare_file_product(libchicken_a)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        chicken,
        "bin/chicken",
    )

    JLLWrappers.@init_file_product(
        chicken_config_h,
        "include/chicken/chicken-config.h",
    )

    JLLWrappers.@init_file_product(
        chicken_h,
        "include/chicken/chicken.h",
    )

    JLLWrappers.@init_library_product(
        libchicken,
        "lib/libchicken.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        chicken_csc,
        "bin/csc",
    )

    JLLWrappers.@init_executable_product(
        chicken_csi,
        "bin/csi",
    )

    JLLWrappers.@init_executable_product(
        chicken_do,
        "bin/chicken-do",
    )

    JLLWrappers.@init_executable_product(
        chicken_install,
        "bin/chicken-install",
    )

    JLLWrappers.@init_executable_product(
        chicken_profile,
        "bin/chicken-profile",
    )

    JLLWrappers.@init_executable_product(
        chicken_status,
        "bin/chicken-status",
    )

    JLLWrappers.@init_executable_product(
        chicken_uninstall,
        "bin/chicken-uninstall",
    )

    JLLWrappers.@init_file_product(
        libchicken_a,
        "lib/libchicken.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
